---
title: "DataCleaning"
format: html
editor: visual
---

# DATA CLEANING AND PRESENTATION

## ELECTRICITY PRICES

```{r}

library(readxl)
library(tidyverse)
library(lubridate)
library(dplyr)


elec_raw <- read_excel("EnergyPricesNewVersion.xlsx", sheet = "Data")


electricity_prices <- elec_raw[11:22, ]


col_names <- as.character(electricity_prices[1, ])


period_cols <- which(grepl("-S", col_names))

electricity_prices <- electricity_prices[-1, c(1, period_cols)]

colnames(electricity_prices) <- c("Country", col_names[period_cols])
electricity_prices <- electricity_prices %>% select(Country, matches("2019|2020|2021|2022|2023|2024"))


electricity_prices <- electricity_prices %>%
  mutate(across(-Country, ~as.numeric(.) * 1000))


cat("\n=== ELECTRICITY PRICES ===\n")
print(electricity_prices)

```

## GAS PRICES

```{r}
raw <- read_excel("TTF_Prices.xlsx", skip = 1)


df <- raw %>%
  select(1:2) %>%                    
  rename(date = 1, price = 2) %>%
  mutate(

    date  = as.Date(date, format = "%m/%d/%Y"),
   
    price = as.numeric(gsub(",", "", price))
  )


df_filtered <- df %>%
  filter(date >= as.Date("2019-01-01"),
         date <= as.Date("2024-12-31")) %>%
  mutate(
    year      = year(date),
    month_num = month(date),
    month     = factor(month.abb[month_num], levels = month.abb)
  )


table_year_month <- df_filtered %>%
  select(year, month, month_num, price) %>%
  arrange(year, month_num) %>%
  select(-month_num) %>%
  pivot_wider(
    names_from  = month,
    values_from = price
  ) %>%
  arrange(year)

table_year_month <- table_year_month %>%
  mutate(across(Jan:Dec, as.numeric))


table_year_month_S <- table_year_month %>%
  rowwise() %>%
  mutate(
    S1 = mean(c_across(Jan:Jun), na.rm = TRUE),
    S2 = mean(c_across(Jul:Dec), na.rm = TRUE)
  ) %>%
  ungroup()


table_semesters <- table_year_month_S %>%
  select(year, S1, S2) %>%
  pivot_longer(
    cols      = c(S1, S2),
    names_to  = "semester",
    values_to = "price"
  ) %>%
  arrange(year, semester)


table_year_month_S

```

```{r}

library(writexl)


write_xlsx(
  electricity_prices,
  path = "Energypricescleaned.xlsx"
)

write_xlsx(
  table_year_month_S,
  path = file.path(getwd(), "Gaspricescleaned.xlsx")
)

```

## IMPORTATIONS

```{r}
library(tidyr)
Imports_pipeline <- read.csv("data/imports_pipeline.csv")

Imports_pipeline <- Imports_pipeline[,-c(1,2,3,4,5,6,10,11)]
Imports_pipeline <- Imports_pipeline |> rename(Country = geo, Year= TIME_PERIOD, pipeline_MCM = OBS_VALUE)

```

```{r}

LNG_2019 <- read.csv2("data/LNG_2019.csv", fileEncoding = "UTF-8")
LNG_2019 <- LNG_2019[-c(1,2,4,5,6,8,9,10,11,14,15,16,17,18,19,20,21),-c(2,3,4,6,7,9)]
LNG_2019 <- pivot_wider(LNG_2019, names_from = Reporter, values_from = Quantity)

LNG_2020 <- read.csv2("data/LNG_2020.csv", fileEncoding = "UTF-8")
LNG_2020 <- LNG_2020[-c(1,2,3,4,5,7,9,10,13,14,15,16,17,18,19,20,21),-c(2,3,4,6,7,9)]
LNG_2020 <- pivot_wider(LNG_2020, names_from = Reporter, values_from = Quantity)

LNG_2021 <- read.csv2("data/LNG_2021.csv", fileEncoding = "UTF-8")
LNG_2021 <- LNG_2021[-c(1,2,3,5,8,9,10,11,12,13,16:23),-c(2,3,4,6,7,9)]
LNG_2021 <- pivot_wider(LNG_2021, names_from = Reporter, values_from = Quantity)

LNG_2022 <- read.csv2("data/LNG_2022.csv", fileEncoding = "UTF-8")
LNG_2022 <- LNG_2022[-c(1,2,4,7:13,15,16,18:25),-c(2,3,4,6,7,9)]
LNG_2022 <- pivot_wider(LNG_2022, names_from = Reporter, values_from = Quantity)

LNG_2023 <- read.csv2("data/LNG_2023.csv", fileEncoding = "UTF-8")
LNG_2023 <- LNG_2023[-c(1:3,6,8:13,15,17:23),-c(2,3,4,6,7,9)]
LNG_2023 <- pivot_wider(LNG_2023, names_from = Reporter, values_from = Quantity)

LNG_2024 <- read.csv2("data/LNG_2024.csv", fileEncoding = "UTF-8")
LNG_2024 <- LNG_2024[-c(1:3,6,7,9:12,14,16:20),-c(2,3,4,6,7,9)]
LNG_2024 <- pivot_wider(LNG_2024, names_from = Reporter, values_from = Quantity)

```

```{r}
LNG_imports <- bind_rows(LNG_2019, LNG_2020, LNG_2021, LNG_2022, LNG_2023, LNG_2024)
LNG_imports <- LNG_imports |> mutate(across(-Year,~as.numeric(.x))) 
LNG_imports[is.na(LNG_imports)]<-0

Density_LNG <- 450
LNG_imports <- LNG_imports |> mutate(across(-Year,~as.numeric(.x)/(Density_LNG * 1000000)))

LNG_imports <- LNG_imports |> slice(rep(1:nrow(LNG_imports), each = 12)) |> mutate(Month=rep(1:12, times = nrow(LNG_imports)), across(-c(Year, Month), ~.x/12), Year = str_c(Year, str_pad(Month, 2, pad="0"), sep = "-")) |> select(-Month)

LNG_imports <- LNG_imports |> pivot_longer(cols= -Year, names_to = "Country", values_to = "LNG_MCM")
```

```{r}
all_keys <- Imports_pipeline |> distinct(Year, Country)

LNG_imports <- all_keys |> left_join(LNG_imports, by = c("Year", "Country")) 
LNG_imports[is.na(LNG_imports)]<- 0
```

```{r}
Total_imports <- Imports_pipeline |> left_join(LNG_imports, by = c("Year", "Country"))
Total_imports <- Total_imports |> mutate(Total_MCM = pipeline_MCM + LNG_MCM)
write.csv(Total_imports, "Total_import.csv", row.names = FALSE)

```

## ELECTRICITY PRODUCTION BY SOURCE

```{r}
Combustible_fuels <- read.csv("data/Combustible_fuels.csv")
Combustible_fuels <- Combustible_fuels[,c(4,6,7,8)] 
Combustible_fuels <- rename(Combustible_fuels, Source = siec, Country = geo, Year = TIME_PERIOD, Electricity_prod = OBS_VALUE)

Hydro <- read.csv("data/Hydro.csv")
Hydro <- Hydro[,c(4,6,7,8)] 
Hydro <- rename(Hydro, Source = siec, Country = geo, Year = TIME_PERIOD, Electricity_prod = OBS_VALUE)

Natural_gas <- read.csv("data/Natural_gas.csv")
Natural_gas <- Natural_gas[,c(4,6,7,8)] 
Natural_gas <- rename(Natural_gas, Source = siec, Country = geo, Year = TIME_PERIOD, Electricity_prod = OBS_VALUE)

Nuclear <- read.csv("data/Nuclear.csv")
Nuclear <- Nuclear[,c(4,6,7,8)] 
Nuclear <- rename(Nuclear, Source = siec, Country = geo, Year = TIME_PERIOD, Electricity_prod = OBS_VALUE)

Renewables <- read.csv("data/Renewable.csv")
Renewables <- Renewables[,c(4,6,7,8)] 
Renewables <- rename(Renewables, Source = siec, Country = geo, Year = TIME_PERIOD, Electricity_prod = OBS_VALUE)

Solar <- read.csv("data/Solar.csv")
Solar <- Solar[,c(4,6,7,8)] 
Solar <- rename(Solar, Source = siec, Country = geo, Year = TIME_PERIOD, Electricity_prod = OBS_VALUE)

Wind <- read.csv("data/Wind.csv")
Wind <- Wind[,c(4,6,7,8)] 
Wind <- rename(Wind, Source = siec, Country = geo, Year = TIME_PERIOD, Electricity_prod = OBS_VALUE)

Total <- read.csv("data/Total.csv")
Total <- Total[,c(4,6,7,8)] 
Total <- rename(Total, Source = siec, Country = geo, Year = TIME_PERIOD, Electricity_prod = OBS_VALUE)
```

```{r}
all_sources <- bind_rows(Combustible_fuels, Hydro, Solar, Wind, Nuclear, Natural_gas, Renewables,Total)

all_sources <- all_sources |> pivot_wider(names_from = "Source", values_from = "Electricity_prod")

sources_list <- split(all_sources, all_sources$Country)


```




